### ISSUE TITLE
Speed up install times for dependencies

### ISSUE THREAD

**Issue by naganowl** [tad-lispy/npm-git-install#12]
I'm noticing if I switch b/w different SHAs or branches for a specified dependency in `gitDependencies`, it takes ~5 minutes to install. It seems like this is because of the dependencies of the source package it has to reinstall which should be able to leverage the cache since the package is mostly the same.

**Comment by tad-lispy** [comment]
Hello, @naganowl.

I agree it would be nice to speed things up. We are using NPM under the hood, so it's caching mechanism should be used. However every time the npm-git installs (or re-installs) a package a new temporary directory is used. It seems to me that changing this aspect would require careful thought. I am open for PRs though :)
