### ISSUE TITLE
Mention exogen/postinstall-build as an alternative

### ISSUE THREAD

**Issue by tad-lispy** [tad-lispy/npm-git-install#13]
Mention exogen/postinstall-build as an alternative in a readme or somehwere.

Are there other alternatives?

**Comment by stereobooster** [comment]
[Yarn is potential alternative](https://github.com/yarnpkg/yarn/issues/2875). I hope 🙏

**Comment by tad-lispy** [comment]
Apparently not yet. Let's hope it will get fixed soon.

**Comment by tad-lispy** [comment]
Hey! Thanks for engaging with my project. It's been a while and I'm pretty sure the issue is not relevant to any of you (see https://github.com/npm/npm/issues/3055#issuecomment-304698029). Please let me know otherwise. Closing.
