### ISSUE TITLE
lib directory is empty

### ISSUE THREAD

**Issue by irakli-lekishvili** [tad-lispy/npm-git-install#16]
This package does'n seem to work for my me, node_modules/package/lib folder is empty, but it compiles in temporary directory 

npm version: 3.10.8

**Comment by tad-lispy** [comment]
Hello, @lekishvili. Thanks for reporting.

Could you please share your `package.json` file?

**Comment by irakli-lekishvili** [comment]
[parent](https://gist.github.com/lekishvili/6de8272cf0c2ad7cac5b22fc22d83a07)
[child](https://gist.github.com/lekishvili/5cea93fd667385da1607a86f4974948a)

**Comment by irakli-lekishvili** [comment]
Can I provide something more to help to reproduce issue?

**Comment by tad-lispy** [comment]
Can you assert that the `lib` folder is populated inside the temporary directory?

Also can you follow the manual installation steps below and tell us what are the effects?

``` sh
git clone <child-repo-url> child
cd child/
npm install
ls lib/
cd ../parent
npm install ../child
```

This is what the `npm-git` is actually doing. Of course you may need to adjust the paths to your setup.

**Comment by irakli-lekishvili** [comment]
Yes lib folder inside tmp directory contains correctly compiled index.js file. 

```
git clone <child-repo-url> child
cd child/
npm install
ls lib/
```

lib directory have index.js with invalid content.

`npm install ../child` what do you mean exactly? `npm install node_modeules/child` ?

**Comment by tad-lispy** [comment]
No, I mean `npm install <dir>`, where `<dir>` stands for a path to the directory where child project is cloned. For example, if you have a directory structure like this:

```
~/projects/parent
~/projects/child
```

then do:

```
cd ~/projects/parent
npm install ~/projects/child
```

In other words: install a package from a local directory. This is what `npm-git` is doing  - it clones the project to local (temporary) directory and installs from there. By asking you to do this _manually_ I am hoping to pinpoint the problem. Otherwise it's hard to guess what is going wrong without having access to your repositories.

**Comment by irakli-lekishvili** [comment]
I see.
Something is very strange, prepublish script(webpack --mode=build) runs successfully but lib directory is still empty

```
> child@1.0.0 prepublish /home/development/child
> webpack --mode=build

Hash: 186c74e90512f8afd9cf
Version: webpack 1.13.2
Time: 3345ms
   Asset     Size  Chunks             Chunk Names
index.js  2.83 kB       0  [emitted]  main
    + 1 hidden modules
```

**Comment by irakli-lekishvili** [comment]
My bad, .npmignore was missing in my child application. I just created empty .npmignore file and everything works as expected. Thank you so much.

**Comment by tad-lispy** [comment]
No problem. Glad that it works for you.

This (mis)feature of NPM did bite me in the past as well. Got to remember that it skips whatever is in `.gitignore` unless `.npmignore` is present or  [`files` is specified in `package.json`](https://docs.npmjs.com/files/package.json#files).
