### ISSUE TITLE
React fixed-data-table issue

### ISSUE THREAD

**Issue by sepo-one** [tad-lispy/npm-git-install#17]
For the repo: [fixed-data-table](https://github.com/facebook/fixed-data-table) npm-git install doesn't work.
Neither does it work if i try to clone this repo to local location and npm install from there.
Seems like [buildNPMInternals.sh](https://github.com/facebook/fixed-data-table/blob/master/build_helpers/buildNPMInternals.sh) doesn't run when installing from local package

**Comment by sepo-one** [comment]
seems like they don't have custom publish. i've added "prepublish" to a fork and it worked.

**Comment by tad-lispy** [comment]
I'm glad to hear that it works for you :)
