### ISSUE TITLE
Do not npm-git-install package if already installed

### ISSUE THREAD

**Issue by sepo-one** [tad-lispy/npm-git-install#18]
Is it possible to do the same as npm does.
So, i would expect, on npm install, if "gitDependencies" holds a package already installed,
no need to reinstall (git clone -> copy -> npm install) every time because it is time consuming.
We could simply check to see if package is already in node_modules.

**Comment by tad-lispy** [comment]
Hey, @sepo-one! I'm open for a PR here.
