### ISSUE TITLE
Spawn command doesn't work on windows

### ISSUE THREAD

**Issue by mattvaughan** [tad-lispy/npm-git-install#19]
After `npm install`, my git repo gets pulled down and after switching to the correct branch it errors out with `Error: spawn npm ENOENT`.

`npm install` works fine for my project on Linux, but I think the issue on windows is related to:
https://github.com/nodejs/node-v0.x-archive/issues/2318

Perhaps change to https://www.npmjs.com/package/cross-spawn ?

**Comment by tad-lispy** [comment]
Thanks for reporting @m0v0nage. It's a genuine concern. Would you open a PR for that?

**Comment by mattvaughan** [comment]
Ya I'll see if I can get to it tonight
