### ISSUE TITLE
Update nodegit

### ISSUE THREAD

**Issue by kintel** [tad-lispy/npm-git-install#2]
npm-git-install fails for me (node 5.6 on Mac) as it's using an old version of nodegit.
Any change you could upgrade to latest?

FYI: I'm using this to work around [NPM issue #3055](https://github.com/npm/npm/issues/3055). Seems like a pretty clean workaround :)

**Comment by tad-lispy** [comment]
Hello. Thanks for using and filing an issue.

It should be relatively easy to do. How about a PR?

**Comment by tad-lispy** [comment]
Thanks for the PR. Merged into master and published to NPM as 0.1.3.
