### ISSUE TITLE
Only works with branch names, not commit hashes

### ISSUE THREAD

**Issue by marnen** [tad-lispy/npm-git-install#7]
If I try to put the following in `gitDependencies`:

```
    "octokat": "https://github.com/divdavem/octokat.js.git#b095a62"
```

then I get `[Error: Reference 'refs/remotes/origin/b095a62' not found]`. Same with a long SHA. Can we make this work?

**Comment by tad-lispy** [comment]
Hello. Thanks for reporting this. I'll try to get to it on the weekend.

**Comment by tad-lispy** [comment]
This should work in #9 - can you follow the instructions in this PR and let me know if it works for you? Thanks and sorry for taking that long.
